services:
  - type: web
    name: futurepath-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        value: mongodb+srv://admin:admin123@cluster0.mongodb.net/futurepath?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: futurepath_secret_key_12345
      - key: OPENAI_API_KEY
        value: YOUR_OPENAI_API_KEY
